### ISSUE TITLE
CondaValueError: prefix already exists:

### ISSUE THREAD

**Issue by hamidj2019** [kvos/CoastSat#22] opened 2019-06-19 03:43 UTC
Hi,
When trying to type the following "conda env create -f environment.yml -n coastsat" in the same folder as "environment.yml" exists which is in **master folder** 
.........CoastSat-master>conda env create -f environment.yml -n coastsat
a message appears as 
CondaValueError: prefix already exists: C:\Users\........\Anaconda3\envs\coastsat

Any idea why this happens?

**Comment by kvos** [comment] 2019-06-19 04:18
duplicate of #18

**Closed** 2019-06-19 04:18 UTC
Labels: duplicate
