### ISSUE TITLE
Error when runnning batch shoreline detection

### ISSUE THREAD

**Issue by Ziene** [kvos/CoastSat#70] opened 2020-02-02 09:10 UTC
Hi,
  This has been a frequent problem of mine. Whenever i press the right arrow which says keep
![wrong narra](https://user-images.githubusercontent.com/60566848/73605838-46235b80-45de-11ea-8663-6bb1d0d17fc1.png) i get this error
![coastsat problem](https://user-images.githubusercontent.com/60566848/73605850-6e12bf00-45de-11ea-84cc-0ce8a836af7d.png). The mapping is stuck at 14%

 I run everything normally except i skip the optional code where it asks me to save it as a jpg because it errors.

I expected it to make a graph after i press keep.

Im running windows 10 pro, and using miniconda3.

**Comment by kvos** [comment] 2020-02-02 20:52
Ok can you run it again but change `settings['save_figure']` to `False` ?
I just want to check if the issue is only saving the figures or something else

**Comment by Ziene** [comment] 2020-02-03 11:57
Wat that fixed everything lol Thank youu

**Comment by kvos** [comment] 2020-02-04 02:57
ok good, but you may still have an issue somewhere because it should be able to save those .jpg files. I'll close the issue now but feel free to re-open it if the issue persists

**Closed by kvos** 2020-02-04 02:57 UTC
Labels: bug
