### ISSUE TITLE
Sklearn issue

### ISSUE THREAD

**Issue by KDUPrasadh** [kvos/CoastSat#188] opened 2021-02-21 14:23 UTC
In Batch shoreline detection has some issues when it run in example_jupyter.ipynb file. I pasted the error massage in following,

Mapping shorelines:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-41-78c4e5dc2bfe> in <module>
      1 get_ipython().run_line_magic('matplotlib', 'qt')
----> 2 output = SDS_shoreline.extract_shorelines(metadata, settings)

~\anaconda3\envs\Coastsat\CoastSat-master\coastsat\SDS_shoreline.py in extract_shorelines(metadata, settings)
    123         elif satname == 'S2':
    124             pixel_size = 10
--> 125             clf = joblib.load(os.path.join(filepath_models, 'NN_4classes_S2.pkl'))
    126 
    127         # convert settings['min_beach_area'] and settings['buffer_size'] from metres to pixels

~\anaconda3\envs\Coastsat\lib\site-packages\joblib\numpy_pickle.py in load(filename, mmap_mode)
    583                     return load_compatibility(fobj)
    584 
--> 585                 obj = _unpickle(fobj, filename, mmap_mode)
    586     return obj

~\anaconda3\envs\Coastsat\lib\site-packages\joblib\numpy_pickle.py in _unpickle(fobj, filename, mmap_mode)
    502     obj = None
    503     try:
--> 504         obj = unpickler.load()
    505         if unpickler.compat_mode:
    506             warnings.warn("The file '%s' has been generated with a "

~\anaconda3\envs\Coastsat\lib\pickle.py in load(self)
   1208                     raise EOFError
   1209                 assert isinstance(key, bytes_types)
-> 1210                 dispatch[key[0]](self)
   1211         except _Stop as stopinst:
   1212             return stopinst.value

~\anaconda3\envs\Coastsat\lib\pickle.py in load_global(self)
   1524         module = self.readline()[:-1].decode("utf-8")
   1525         name = self.readline()[:-1].decode("utf-8")
-> 1526         klass = self.find_class(module, name)
   1527         self.append(klass)
   1528     dispatch[GLOBAL[0]] = load_global

~\anaconda3\envs\Coastsat\lib\pickle.py in find_class(self, module, name)
   1575             elif module in _compat_pickle.IMPORT_MAPPING:
   1576                 module = _compat_pickle.IMPORT_MAPPING[module]
-> 1577         __import__(module, level=0)
   1578         if self.proto >= 4:
   1579             return _getattribute(sys.modules[module], name)[0]

ModuleNotFoundError: No module named 'sklearn.neural_network.multilayer_perceptron'

Please help me to solve this issue.

**Comment by kvos** [comment] 2021-02-26 01:13
I found this https://stackoverflow.com/questions/61177448/no-module-named-sklearn-neural-network-multilayer-perceptron maybe try that solution and see how you go

**Comment by KDUPrasadh** [comment] 2021-02-27 02:19
Thank you very much. Please, May I obtain a cookbook for Coastsat which are included all important steps in classification, shoreline extraction and etc.

**Comment by KDUPrasadh** [comment] 2021-02-27 06:03
I did "conda update scikit-learn".
But still error remain.

**Comment by alscatS** [comment] 2021-03-11 12:57
I had to >conda install joblib<
edit line >from sklearn.externals import joblib< from SDS_shoreline.py to >import joblib<
just to get the first block of code to run!

I am now stuck in same place of 'Batch shoreline detection' with the error of:
 "ModuleNotFoundError: No module named 'sklearn.externals.joblib'" - which is the error I got from code block one and the solution i found: https://stackoverflow.com/questions/61893719/importerror-cannot-import-name-joblib-from-sklearn-externals... for code block 1. 

I performed the update on conda scikit-learn

**Comment by kvos** [comment] 2021-03-12 00:17
thanks @alscatS  for your feedback, I think I know what is going on there. Joblib is used to save and load the neural networks models into binary files. It used to be included in scikit-learn (externals.joblib) but now it is not anymore and users should use the joblib package directly. The issue is that the models were created with an old version of joblib and cannot be loaded with the new version, so I need to save the models again with the new version of joblib so that they can be loaded. Will try to make this update soon

**Comment by kvos** [comment] 2021-03-13 10:07
@alscatS @KDUPrasadh if you could please try the latest development branch, this issue should be fixed on that version, let me know how it goes, thanks

**Comment by kvos** [comment] 2021-04-06 02:14
this should be fixed by now in the new release, feel free to reopen this issue if it persists

**Closed by kvos** 2021-04-06 02:14 UTC
