### ISSUE TITLE
Error while merging overlapping S2 images

### ISSUE THREAD

**Issue by wreys** [kvos/CoastSat#161] opened 2020-12-08 05:42 UTC
Hi, thanks for making public your code.

I have been using your code for the Northwest of Yucatan, Mexico. I have experienced an error related to merging overlapping when using S2 images. I am downloading L8 and S2 separately. For the same polygon (see below) when I switch from S2 to L8 images, the error disappears. Something awkward is happening when using S2 images.  When I use only two years using S2, there is no issue, but when I increase to 3 more years, a warning appears "WARNING: there was an error while merging overlapping S2 images, please open an issue on Github at https://github.com/kvos/CoastSat/issues and include your script so we can find out what happened." That warning does not let me move forward.

Could you please tell me how may I solve that issue when downloading S2 images? 
I guess the polygon is fine because L8 images are downloading very well, the issue occurred when I try to download S2 images. This is the code that I am using:

# region of interest (longitude, latitude)
polygon = [[[-90.22, 21.06],
            [-90.11, 21.13],
            [-90.12, 21.15],  
            [-90.23, 21.09],
            [-90.22, 21.06]]] 
# it's recommended to convert the polygon to the smallest rectangle (sides parallel to coordinate axes)       
polygon = SDS_tools.smallest_rectangle(polygon)
# date range
dates = ['2015-01-01', '2018-01-01']
# satellite missions
sat_list = ['S2']
# name of the site
sitename = 'Palmar2015_2018_S2P1'
# directory where the data will be stored
filepath = os.path.join(os.getcwd(), 'data')
# put all the inputs into a dictionnary
inputs = {'polygon': polygon, 'dates': dates, 'sat_list': sat_list, 'sitename': sitename, 'filepath':filepath}

# before downloading the images, check how many images are available for your inputs
SDS_download.check_images_available(inputs);

Additionally, when I increase a little the polygon to the west (see below), I can download L8 images very well, but when I switch to S2 images, it does not download anything.

-90.33 | 20.99
-90.11 | 21.13
-90.12 | 21.15
-90.34 | 21.02
-90.33 | 20.99

Thanks for your time

**Comment by kvos** [comment] 2020-12-08 22:57
ok thanks for letting me know, I knew there may be a problem with that overlapping function so I made it raise that warining. Will test it out and let you know how to fix it. In the meanwhile you can go in SDS_download.py and comment lines 280 to 286, then it will not merge the S2 images and you can continue processing.

**Comment by kvos** [comment] 2020-12-08 23:02
I just tried with a few dates and it merged them correctly, will try with the same dates as you to see if I can replicate the error.

BTW, this beach looks just magic!
![image](https://user-images.githubusercontent.com/7217258/101551605-60e80d00-3a05-11eb-9646-727aae08c08a.png)

**Comment by wreys** [comment] 2020-12-08 23:13
Thank you! Yes, if you use up to two years there is not a problem. However, if you use 3 o more years the merge warning appears. It does not occur when using L8 images....why?
b) I just downloaded L8 images for the following polygon but when using S2, it does not download anything. Any reason? 

Thanks a lot!


polygon = [[[-90.33, 20.99],
            [-90.11, 21.13],
            [-90.12, 21.15],  
            [-90.34, 21.02],
            [-90.33, 20.99]]] 
# it's recommended to convert the polygon to the smallest rectangle (sides parallel to coordinate axes)       
polygon = SDS_tools.smallest_rectangle(polygon)
# date range
dates = ['2015-01-01', '2020-11-23']
# satellite missions
sat_list = ['L8']
# name of the site

**Comment by kvos** [comment] 2020-12-09 00:21
the issue is on the 22nd June 2016 (2016-06-22), there are 4 overlapping images at your site, the function could only handle 3 so it's throwing an error, will try to fix that when I have time. In the meanwhile you can download all images without merging overlapping images, then manually remove that date (all 4 images) and then merge the overlapping images.

**Comment by kvos** [comment] 2020-12-09 00:57
just did an update #162 and it now works fine with quadruplicates like at your site. You can download the latest version and it should be all good, let me know

**Comment by wreys** [comment] 2020-12-09 21:46
Thank you! For the polygon you used (configuration 1), it works fine with quadruplicates. However, when I make bigger the polygon (see configuration 2) , the dowloading does not start for S2 imagenes. For L8 the downloads work wel for both polygones (configuration 1 & 2). Any away, it is no t a big deal. I can split the bigger polygon in two. Then, it works well for S2 images. Thanks for your support!

configuration 1:
# region of interest (longitude, latitude)
polygon = [[[-90.22, 21.06],
            [-90.11, 21.13],
            [-90.12, 21.15],  
            [-90.23, 21.09],
            [-90.22, 21.06]]] 
# it's recommended to convert the polygon to the smallest rectangle (sides parallel to coordinate axes)       
polygon = SDS_tools.smallest_rectangle(polygon)
# date range
dates = ['2015-01-01', '2020-11-23']
# satellite missions
sat_list = ['S2']

configuration2:
polygon = [[[-90.33, 20.99],
            [-90.11, 21.13],
            [-90.12, 21.15],  
            [-90.34, 21.02],
            [-90.33, 20.99]]] 
# it's recommended to convert the polygon to the smallest rectangle (sides parallel to coordinate axes)       
polygon = SDS_tools.smallest_rectangle(polygon)
# date range
dates = ['2015-01-01', '2020-11-23']
# satellite missions
sat_list = ['S2']

**Comment by kvos** [comment] 2020-12-10 01:39
ok good that it works now. Yes it's good practice to split polygons (always keep smaller than 100 square km) as otherwise you may encounter slow processing and memory errors. I'll have a go with configuration 2 but if it's too big it's better to split it.

**Closed** 2020-12-22 22:52 UTC
