### ISSUE TITLE
issue with output_to_gdf  UnboundLocalError: local variable 'gdf_all' referenced before assignment

### ISSUE THREAD

**Issue by HSdouma** [kvos/CoastSat#147] opened 2020-10-13 11:33 UTC
Hi Kvos 
What is the source of this error  when trying to run gdf = SDS_tools.output_to_gdf(output, geomtype)

File "D:\CoastSat-1.0.5\coastsat\SDS_tools.py", line 648, in output_to_gdf

UnboundLocalError: local variable 'gdf_all' referenced before assignment

many thanks

**Comment by kvos** [comment] 2020-10-14 03:32
hey @HSdouma 
Not sure what is going on there, are you using the latest version of CoastSat? The code for that function is below, I think the only way that gdf_all doesn't get initialised properly is if your output variable is empty, could this be the case?
```   
# loop through the mapped shorelines
    counter = 0
    for i in range(len(output['shorelines'])):
        # skip if there shoreline is empty 
        if len(output['shorelines'][i]) == 0:
            continue
        else:
            # save the geometry depending on the linestyle
            if geomtype == 'lines':
                geom = geometry.LineString(output['shorelines'][i])
            elif geomtype == 'points':
                coords = output['shorelines'][i]
                geom = geometry.MultiPoint([(coords[_,0], coords[_,1]) for _ in range(coords.shape[0])])
            else:
                raise Exception('geomtype %s is not an option, choose between lines or points'%geomtype)
            # save into geodataframe with attributes
            gdf = gpd.GeoDataFrame(geometry=gpd.GeoSeries(geom))
            gdf.index = [i]
            gdf.loc[i,'date'] = output['dates'][i].strftime('%Y-%m-%d %H:%M:%S')
            gdf.loc[i,'satname'] = output['satname'][i]
            gdf.loc[i,'geoaccuracy'] = output['geoaccuracy'][i]
            gdf.loc[i,'cloud_cover'] = output['cloud_cover'][i]
            # store into geodataframe
            if counter == 0:
                gdf_all = gdf
            else:
                gdf_all = gdf_all.append(gdf)
            counter = counter + 1
            
    return gdf_all
```

**Comment by HSdouma** [comment] 2020-10-14 07:59
Hi Kvos
you are fully right. nothing wrong with the code, my detected shorline is empty. I am wondering why? could this be related to the very narrow beach that i am working with or to the training? 
I am working with images where the beach thickness does not exceed 50 m. 
However, the program detects some beaches in the inlands of the images, can this be related to the training ?
Many thanks

**Comment by kvos** [comment] 2020-10-14 10:51
could be many things. are you using a reference shoreline? what is the minimum shoreline length set to? which coordinate system are you using?

**Comment by HSdouma** [comment] 2020-10-14 11:04
Yes I am using a reference shoreline. The minimum length is set to 100m. Epsg 4326 wgs 84. Also, I have set the minimum area for a beach to be considered to 50 m square.

**Comment by HSdouma** [comment] 2020-10-14 12:43
Hi Kvos
Yes I am using a reference shoreline. The minimum length of the shoreline is 100m. The coordinate system is Epsg 4326 wgs 84. Also the minimum area for a beach is set 50 m square.

**Comment by kvos** [comment] 2020-10-14 22:56
ok perfect, that's easy to spot, the issue is epsg 4326. You need to use projected coordinates (i.e. cartesian). WGS84 are spherical lat/lon coordinates which are not compatible with the geometric operations that are implemented in coastsat (it's using the shapely library which requires cartesian coordinates). Please everybody read the documentation!

**Comment by kvos** [comment] 2020-11-17 23:41
will close this issue for the time being, feel free to reopen if it's not solved

**Closed by kvos** 2020-11-17 23:41 UTC
