### ISSUE TITLE
Improve download functionality to avoid re-downloading existing images

### ISSUE THREAD

**Issue by eddylr** [kvos/CoastSat#333] opened 2022-09-30 01:43 UTC
Hi Kilian,

I tried the new update on the downloading scripts but some sites gave an issue with S2 mission, particularly  on duplicates . Here’s  a picture of the error:
![image](https://user-images.githubusercontent.com/110738991/193172016-b4777c8d-d10d-44c4-8512-99c94d969ebb.png)

Also, it seems script no longer overwrites already existing downloaded files.
Thanks,
Eddy R.

**Comment by kvos** [comment] 2022-09-30 03:11
it seems to be the same issue as #331 with Sentinel-2 duplicates. Maybe I should revert to the previous version until this duplicate thing is fixed. Can you pls provide a full description of the issue (inputs) so I can reproduce it? thanks

**Comment by kvos** [comment] 2022-09-30 03:48
ok if it was the same issue as #331 , it should be fixed now, try the latest version and let me know

**Comment by eddylr** [comment] 2022-09-30 16:18
Thank you, Kilian. The duplicate issue is now solved.

My second comment refers to having to manually delete previously downloaded files when re-running the download command when an error occurred during process. I think previous versions had an overwrite command on the script. 

Also, I think it would be a good addition to find a way to avoid the download if file is already there. This could  save time when the download process stopped for un-related script issues (i.e. connection issue) or if you want to update  the time-range of the files.

Thanks again, 
Eddy R.

**Comment by kvos** [comment] 2022-10-04 23:20
yes I agree that there is something funky going on with the perimissions and overwrites in the new version. The feature you suggested makes sense, could you pls open a new issue labelled as `enhancement` with this suggestion? Then I'll close this issue on duplicates and keep the other one open.

**Comment by kvos** [comment] 2023-12-18 05:23
this enhancement has been implemented.

**Closed by kvos** 2023-12-18 05:23 UTC
Labels: enhancement
